# Generated by Django 3.0.6 on 2020-05-27 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Average'), ('D', 'Poor'), ('F', 'Fail')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('type', models.CharField(choices=[('FA', 'Fall'), ('SP', 'Spring')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='MemberGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='general.Course', verbose_name='list of courses')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Grade')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Professor'),
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='membergrades',
            field=models.ManyToManyField(to='general.MemberGrades', verbose_name='list of grades'),
        ),
    ]
