# Generated by Django 3.0.6 on 2020-05-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20200528_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='membergrades',
            field=models.ManyToManyField(blank=True, to='general.MemberGrades', verbose_name='list of grades'),
        ),
    ]
