# Generated by Django 3.0.6 on 2020-05-31 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20200531_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberinfo',
            name='membergrades',
        ),
    ]
