# Generated by Django 3.0.6 on 2020-06-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_department_departmentprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='regopen',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
