# Generated by Django 3.0.6 on 2020-06-05 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_auto_20200604_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='general.Semester'),
            preserve_default=False,
        ),
    ]
