# Generated by Django 3.0.6 on 2020-06-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_auto_20200605_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='registrationstatus',
            field=models.CharField(choices=[('RE', 'Registered'), ('UR', 'Unregistered')], default='UR', max_length=12),
        ),
    ]
