# Generated by Django 3.0.6 on 2020-06-15 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_auto_20200606_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('lectureno', models.IntegerField()),
                ('videofile', models.FileField(null=True, upload_to='lectures/', verbose_name='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='general.Course')),
            ],
        ),
    ]
