# Generated by Django 3.0.6 on 2020-06-18 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0018_auto_20200618_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='writer',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
