# Generated by Django 3.0.6 on 2020-06-19 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_announcement_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
    ]
